dist: trusty
sudo: required
language: python
python:
  - "2.7"
# dependencies for pyaudio
before_install:
  - "sudo apt-get install libjack-jackd2-dev portaudio19-dev"
# command to install dependencies
install: "pip install -r ./source/requirements.txt"
# command to run tests
script: python ./source/ImpulseTest.py '/dev/ttyS0' ./assets/song.wav
