dist: trusty
sudo: required
language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r ./source/requirements.txt"
# command to run tests
script: python ./source/ImpulseTest.py
